# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70545b4872c2e0d73ba40a109873007cda08d2dfc8cbcda3b679ae69a28f60be64b784e6181b8a362602df02b8ad58f35722beaf8497dd60bc49ebd946ab0bdc

test:
  secret_key_base: 7864dc14a51f3c4ea6eda2d251c5ac550d9d7a39000f49c230f724528e9114fba38c05b61270afaa2a90c5010ce3e27f6b1a8d896d7de2adbd4668371bdb86c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
